services:
  web:
    image: ghcr.io/echo-sols-ltd/umuhinzilink-web:latest
    environment:
      - NODE_ENV=production
    network_mode: host
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:7023",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
