/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './providers/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Agricultural Primary Colors
        agricultural: {
          primary: 'var(--agricultural-primary)',
          'primary-light': 'var(--agricultural-primary-light)',
          'primary-lighter': 'var(--agricultural-primary-lighter)',
          'primary-lightest': 'var(--agricultural-primary-lightest)',
          50: 'var(--agricultural-green-50)',
          100: 'var(--agricultural-green-100)',
          200: 'var(--agricultural-green-200)',
          300: 'var(--agricultural-green-300)',
          400: 'var(--agricultural-green-400)',
          500: 'var(--agricultural-green-500)',
          600: 'var(--agricultural-green-600)',
          700: 'var(--agricultural-green-700)',
          800: 'var(--agricultural-green-800)',
          900: 'var(--agricultural-green-900)',
        },
        
        // Earth Tone Colors
        earth: {
          brown: {
            DEFAULT: 'var(--earth-brown)',
            light: 'var(--earth-brown-light)',
            50: 'var(--earth-brown-50)',
            100: 'var(--earth-brown-100)',
            200: 'var(--earth-brown-200)',
            300: 'var(--earth-brown-300)',
            400: 'var(--earth-brown-400)',
            500: 'var(--earth-brown-500)',
            600: 'var(--earth-brown-600)',
            700: 'var(--earth-brown-700)',
            800: 'var(--earth-brown-800)',
            900: 'var(--earth-brown-900)',
          },
          ochre: {
            DEFAULT: 'var(--earth-ochre)',
            light: 'var(--earth-ochre-light)',
            50: 'var(--earth-ochre-50)',
            100: 'var(--earth-ochre-100)',
            200: 'var(--earth-ochre-200)',
            300: 'var(--earth-ochre-300)',
            400: 'var(--earth-ochre-400)',
            500: 'var(--earth-ochre-500)',
            600: 'var(--earth-ochre-600)',
            700: 'var(--earth-ochre-700)',
            800: 'var(--earth-ochre-800)',
            900: 'var(--earth-ochre-900)',
          },
          clay: {
            DEFAULT: 'var(--earth-clay)',
            light: 'var(--earth-clay-light)',
            50: 'var(--earth-clay-50)',
            100: 'var(--earth-clay-100)',
            200: 'var(--earth-clay-200)',
            300: 'var(--earth-clay-300)',
            400: 'var(--earth-clay-400)',
            500: 'var(--earth-clay-500)',
            600: 'var(--earth-clay-600)',
            700: 'var(--earth-clay-700)',
            800: 'var(--earth-clay-800)',
            900: 'var(--earth-clay-900)',
          },
        },
        
        // Fresh Accent Colors
        harvest: {
          gold: {
            DEFAULT: 'var(--harvest-gold)',
            light: 'var(--harvest-gold-light)',
            50: 'var(--harvest-gold-50)',
            100: 'var(--harvest-gold-100)',
            200: 'var(--harvest-gold-200)',
            300: 'var(--harvest-gold-300)',
            400: 'var(--harvest-gold-400)',
            500: 'var(--harvest-gold-500)',
            600: 'var(--harvest-gold-600)',
            700: 'var(--harvest-gold-700)',
            800: 'var(--harvest-gold-800)',
            900: 'var(--harvest-gold-900)',
          },
        },
        
        sunrise: {
          orange: {
            DEFAULT: 'var(--sunrise-orange)',
            light: 'var(--sunrise-orange-light)',
            50: 'var(--sunrise-orange-50)',
            100: 'var(--sunrise-orange-100)',
            200: 'var(--sunrise-orange-200)',
            300: 'var(--sunrise-orange-300)',
            400: 'var(--sunrise-orange-400)',
            500: 'var(--sunrise-orange-500)',
            600: 'var(--sunrise-orange-600)',
            700: 'var(--sunrise-orange-700)',
            800: 'var(--sunrise-orange-800)',
            900: 'var(--sunrise-orange-900)',
          },
        },
        
        sky: {
          blue: {
            DEFAULT: 'var(--sky-blue)',
            light: 'var(--sky-blue-light)',
            50: 'var(--sky-blue-50)',
            100: 'var(--sky-blue-100)',
            200: 'var(--sky-blue-200)',
            300: 'var(--sky-blue-300)',
            400: 'var(--sky-blue-400)',
            500: 'var(--sky-blue-500)',
            600: 'var(--sky-blue-600)',
            700: 'var(--sky-blue-700)',
            800: 'var(--sky-blue-800)',
            900: 'var(--sky-blue-900)',
          },
        },
        
        soil: {
          rich: {
            DEFAULT: 'var(--soil-rich)',
            light: 'var(--soil-rich-light)',
            50: 'var(--soil-rich-50)',
            100: 'var(--soil-rich-100)',
            200: 'var(--soil-rich-200)',
            300: 'var(--soil-rich-300)',
            400: 'var(--soil-rich-400)',
            500: 'var(--soil-rich-500)',
            600: 'var(--soil-rich-600)',
            700: 'var(--soil-rich-700)',
            800: 'var(--soil-rich-800)',
            900: 'var(--soil-rich-900)',
          },
        },
        
        // Updated Primary Colors
        primary: {
          DEFAULT: 'var(--agricultural-primary)',
          50: 'var(--agricultural-green-50)',
          100: 'var(--agricultural-green-100)',
          200: 'var(--agricultural-green-200)',
          300: 'var(--agricultural-green-300)',
          400: 'var(--agricultural-green-400)',
          500: 'var(--agricultural-green-500)',
          600: 'var(--agricultural-green-600)',
          700: 'var(--agricultural-green-700)',
          800: 'var(--agricultural-green-800)',
          900: 'var(--agricultural-green-900)',
          light: 'var(--agricultural-primary-light)',
          dark: 'var(--agricultural-green-700)',
        },
        
        // Updated Semantic Colors
        success: {
          DEFAULT: 'var(--growth-success)',
          light: 'var(--growth-success-light)',
          dark: 'var(--growth-success-dark)',
          bg: 'var(--growth-success-bg)',
        },
        warning: {
          DEFAULT: 'var(--caution-yellow)',
          light: 'var(--caution-yellow-light)',
          dark: 'var(--caution-yellow-dark)',
          bg: 'var(--caution-yellow-bg)',
        },
        error: {
          DEFAULT: 'var(--alert-red)',
          light: 'var(--alert-red-light)',
          dark: 'var(--alert-red-dark)',
          bg: 'var(--alert-red-bg)',
        },
        info: {
          DEFAULT: 'var(--info-blue)',
          light: 'var(--info-blue-light)',
          dark: 'var(--info-blue-dark)',
          bg: 'var(--info-blue-bg)',
        },
        gray: {
          50: 'var(--gray-50)',
          100: 'var(--gray-100)',
          200: 'var(--gray-200)',
          300: 'var(--gray-300)',
          400: 'var(--gray-400)',
          500: 'var(--gray-500)',
          600: 'var(--gray-600)',
          700: 'var(--gray-700)',
          800: 'var(--gray-800)',
          900: 'var(--gray-900)',
        },
      },
      backgroundImage: {
        'gradient-primary': 'var(--bg-gradient-primary)',
        'gradient-success': 'var(--bg-gradient-success)',
        'gradient-warning': 'var(--bg-gradient-warning)',
        'gradient-error': 'var(--bg-gradient-error)',
        'gradient-info': 'var(--bg-gradient-info)',
        'gradient-subtle': 'var(--bg-gradient-subtle)',
        'gradient-earth': 'var(--bg-gradient-earth)',
        'gradient-harvest': 'var(--bg-gradient-harvest)',
        'gradient-natural': 'var(--bg-gradient-natural)',
      },
      fontFamily: {
        primary: 'var(--font-primary)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        // Legacy sizes for backward compatibility
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
        '6xl': 'var(--text-6xl)',
        
        // Enhanced responsive typography scale
        'display': 'var(--text-display)',
        'h1': 'var(--text-h1)',
        'h2': 'var(--text-h2)',
        'h3': 'var(--text-h3)',
        'h4': 'var(--text-h4)',
        'h5': 'var(--text-h5)',
        'h6': 'var(--text-h6)',
        'body': 'var(--text-body)',
        'body-lg': 'var(--text-body-lg)',
        'body-sm': 'var(--text-body-sm)',
        'caption': 'var(--text-caption)',
        'label': 'var(--text-label)',
        
        // Agricultural-specific sizes
        'price': 'var(--text-price)',
        'price-large': 'var(--text-price-large)',
        'quantity': 'var(--text-quantity)',
        'measurement': 'var(--text-measurement)',
        'farmer-name': 'var(--text-farmer-name)',
        'location': 'var(--text-location)',
        'status': 'var(--text-status)',
      },
      fontWeight: {
        light: 'var(--font-light)',
        normal: 'var(--font-normal)',
        medium: 'var(--font-medium)',
        semibold: 'var(--font-semibold)',
        bold: 'var(--font-bold)',
        extrabold: 'var(--font-extrabold)',
      },
      lineHeight: {
        tight: 'var(--leading-tight)',
        snug: 'var(--leading-snug)',
        normal: 'var(--leading-normal)',
        relaxed: 'var(--leading-relaxed)',
        loose: 'var(--leading-loose)',
        // Enhanced outdoor readability line heights
        'outdoor-tight': 'var(--leading-outdoor-tight)',
        'outdoor-normal': 'var(--leading-outdoor-normal)',
        'outdoor-relaxed': 'var(--leading-outdoor-relaxed)',
      },
      letterSpacing: {
        tighter: 'var(--tracking-tighter)',
        tight: 'var(--tracking-tight)',
        normal: 'var(--tracking-normal)',
        wide: 'var(--tracking-wide)',
        wider: 'var(--tracking-wider)',
        widest: 'var(--tracking-widest)',
        // Agricultural-specific letter spacing
        agricultural: 'var(--tracking-agricultural)',
      },
      spacing: {
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
        'card-padding': 'var(--card-padding)',
        'section-gap': 'var(--section-gap)',
        'mobile-margin': 'var(--mobile-margin)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        10: 'var(--space-10)',
        11: 'var(--space-11)',
        12: 'var(--space-12)',
        14: 'var(--space-14)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        32: 'var(--space-32)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
        organic: 'var(--radius-organic)',
        card: 'var(--radius-card)',
        button: 'var(--radius-button)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        none: 'var(--shadow-none)',
        'green-xs': 'var(--shadow-green-xs)',
        'green-sm': 'var(--shadow-green-sm)',
        'green-md': 'var(--shadow-green-md)',
        'green-lg': 'var(--shadow-green-lg)',
        'green-xl': 'var(--shadow-green-xl)',
        'earth-sm': 'var(--shadow-earth-sm)',
        'earth-md': 'var(--shadow-earth-md)',
        'earth-lg': 'var(--shadow-earth-lg)',
        'warm-sm': 'var(--shadow-warm-sm)',
        'warm-md': 'var(--shadow-warm-md)',
        'warm-lg': 'var(--shadow-warm-lg)',
      },
      transitionDuration: {
        75: 'var(--duration-75)',
        100: 'var(--duration-100)',
        150: 'var(--duration-150)',
        200: 'var(--duration-200)',
        300: 'var(--duration-300)',
        500: 'var(--duration-500)',
        700: 'var(--duration-700)',
        1000: 'var(--duration-1000)',
      },
      transitionTimingFunction: {
        'ease-linear': 'var(--ease-linear)',
        'ease-in': 'var(--ease-in)',
        'ease-out': 'var(--ease-out)',
        'ease-in-out': 'var(--ease-in-out)',
        'ease-bounce': 'var(--ease-bounce)',
        'ease-spring': 'var(--ease-spring)',
        'ease-elastic': 'var(--ease-elastic)',
        'ease-back': 'var(--ease-back)',
      },
      zIndex: {
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        fixed: 'var(--z-fixed)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        tooltip: 'var(--z-tooltip)',
        toast: 'var(--z-toast)',
      },
      animation: {
        'fade-in': 'fadeIn var(--transition-normal) var(--ease-out)',
        'fade-out': 'fadeOut var(--transition-normal) var(--ease-in)',
        'fade-up': 'fadeUp var(--transition-normal) var(--ease-out)',
        'fade-down': 'fadeDown var(--transition-normal) var(--ease-out)',
        'fade-left': 'fadeLeft var(--transition-normal) var(--ease-out)',
        'fade-right': 'fadeRight var(--transition-normal) var(--ease-out)',
        'scale-in': 'scaleIn var(--transition-normal) var(--ease-bounce)',
        'scale-out': 'scaleOut var(--transition-normal) var(--ease-in)',
        'slide-up': 'slideInUp var(--transition-normal) var(--ease-out)',
        'slide-down': 'slideInDown var(--transition-normal) var(--ease-out)',
        'slide-left': 'slideInLeft var(--transition-normal) var(--ease-out)',
        'slide-right': 'slideInRight var(--transition-normal) var(--ease-out)',
        'bounce': 'bounce 1s infinite',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shake': 'shake 0.5s ease-in-out',
        'spin': 'spin 1s linear infinite',
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
        'shimmer-wave': 'shimmer-wave 1.5s ease-in-out infinite',
        'ripple': 'ripple 0.6s linear',
      },
      keyframes: {
        fadeIn: {
          'from': { opacity: '0' },
          'to': { opacity: '1' },
        },
        fadeOut: {
          'from': { opacity: '1' },
          'to': { opacity: '0' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeDown: {
          '0%': { opacity: '0', transform: 'translateY(-40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeLeft: {
          '0%': { opacity: '0', transform: 'translateX(40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        fadeRight: {
          '0%': { opacity: '0', transform: 'translateX(-40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        scaleOut: {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(0.9)' },
        },
        slideInUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideInDown: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        bounce: {
          '0%, 20%, 53%, 80%, 100%': {
            'animation-timing-function': 'cubic-bezier(0.215, 0.61, 0.355, 1)',
            transform: 'translate3d(0, 0, 0)',
          },
          '40%, 43%': {
            'animation-timing-function': 'cubic-bezier(0.755, 0.05, 0.855, 0.06)',
            transform: 'translate3d(0, -30px, 0)',
          },
          '70%': {
            'animation-timing-function': 'cubic-bezier(0.755, 0.05, 0.855, 0.06)',
            transform: 'translate3d(0, -15px, 0)',
          },
          '90%': { transform: 'translate3d(0, -4px, 0)' },
        },
        pulse: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-10px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(10px)' },
        },
        shimmer: {
          '0%': { 'background-position': '-200px 0' },
          '100%': { 'background-position': 'calc(200px + 100%) 0' },
        },
        'shimmer-wave': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        spin: {
          'from': { transform: 'rotate(0deg)' },
          'to': { transform: 'rotate(360deg)' },
        },
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '1' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
  ],
}