import type { Metadata, Viewport } from 'next'; // Add Viewport import
import { Poppins } from 'next/font/google';
import { AppProviders } from '@/providers/AppProviders';
import './globals.css';

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'], // Add subsets
});

export const metadata: Metadata = {
  title: 'UmuhinziLink',
  description: 'Generated by create next app',
};


export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${poppins.variable} antialiased`}>
      <body className="bg-white text-black">
        <AppProviders>
          <main>{children}</main>
        </AppProviders>
      </body>
    </html>
  );
}