name: Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "Dockerfile"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/docker-publish.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/echo-sols-ltd/umuhinzilink-web:latest